name: para_managment_team
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  cloud_firestore: ^3.1.6
  firebase_analytics: ^9.0.4
  firebase_auth: ^3.3.4
  firebase_core: ^1.10.6
  http: ^0.13.4
  lottie: ^1.2.1
  provider: ^6.0.2
  shared_preferences: ^2.0.12
  uuid: ^3.0.5
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
